{% set name = 'bob.io.image' %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  run_exports:
    - {{ pin_subpackage(name) }}
  script:
    - cd {{ project_dir }}
    {% if environ.get('BUILD_EGG') %}
    - "{{ PYTHON }} setup.py sdist --formats=zip"
    {% endif %}
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config {{ pkg_config }}
    - cmake {{ cmake }}
    - make {{ make }}
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - pip {{ pip }}
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.io.base >=2.0.9
    - libblitz {{ libblitz }}
    - giflib {{ giflib }}
    - libpng {{ libpng }}
    - jpeg {{ jpeg }}
    - libtiff {{ libtiff }}
    - boost {{ boost }}
    - numpy {{ numpy }}
    - matplotlib {{ matplotlib }}
  run:
    - python
    - setuptools
    - boost
    - {{ pin_compatible('numpy') }}
  run_constrained:
    - {{ pin_compatible('matplotlib') }}

test:
  imports:
    - {{ name }}
  commands:
    - nosetests --with-coverage --cover-package={{ name }} -sv {{ name }}
    - sphinx-build -aEW {{ project_dir }}/doc {{ project_dir }}/sphinx
    - sphinx-build -aEb doctest {{ project_dir }}/doc sphinx
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]
  requires:
    - nose {{ nose }}
    - coverage {{ coverage }}
    - sphinx {{ sphinx }}
    - sphinx_rtd_theme {{ sphinx_rtd_theme }}
    - matplotlib

about:
  home: https://www.idiap.ch/software/bob/
  license: BSD 3-Clause
  summary: Image I/O support for Bob
  license_family: BSD
